/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    events: Event;
    services: Service;
    courses: Course;
    testimonials: Testimonial;
    partners: Partner;
    team: Team;
    pages: Page;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'home-page': HomePage;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  thumbnail?: (number | null) | Media;
  category?: ('tin-tuc' | 'su-kien' | 'kien-thuc') | null;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  author?: string | null;
  publishedAt?: string | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  thumbnail?: (number | null) | Media;
  categories?:
    | ('cong-nghe' | 'groups' | 'hop-tac' | 'chuong-trinh-moi' | 'tu-duy-va-cong-cu' | 'hr' | 'learning-development')[]
    | null;
  /**
   * Ngày diễn ra sự kiện
   */
  eventDate?: string | null;
  /**
   * Địa điểm sự kiện
   */
  location?: string | null;
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  status?: ('draft' | 'published') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  slug?: string | null;
  icon?: (number | null) | Media;
  shortDescription?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  slug?: string | null;
  thumbnail?: (number | null) | Media;
  duration?: string | null;
  level?: ('co-ban' | 'trung-cap' | 'nang-cao') | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  price?: number | null;
  isActive?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  name: string;
  position?: string | null;
  company?: string | null;
  avatar?: (number | null) | Media;
  quote?: string | null;
  rating?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  name: string;
  logo: number | Media;
  website?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role?: string | null;
  bio?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path, e.g. "keystone" → /keystone
   */
  slug: string;
  seo?: {
    title?: string | null;
    description?: string | null;
    /**
     * Structured data JSON-LD (schema.org). Dán JSON object hoặc array. Sẽ render <script type="application/ld+json"> trong <head>. Để trống nếu không dùng.
     */
    jsonLdSchema?: string | null;
  };
  layout: (
    | {
        slides?:
          | {
              image: number | Media;
              badge?: string | null;
              headline?: string | null;
              sub?: string | null;
              ctaLabel?: string | null;
              ctaHref?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Auto-advance interval in ms. 0 = disabled.
         */
        autoplayMs?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'heroSlider';
      }
    | {
        breadcrumb?: string | null;
        title: string;
        subtitle?: string | null;
        variant?: ('navy' | 'gold' | 'image') | null;
        backgroundImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'hero';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        keywords?:
          | {
              label: string;
              id?: string | null;
            }[]
          | null;
        blockquote?: string | null;
        /**
         * Optional. When set, renders 2-col text + image layout.
         */
        image?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'intro';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        background?: ('navy' | 'light') | null;
        items?:
          | {
              value: string;
              label: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'stats';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        members?: (number | Team)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'team';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        items?: (number | Testimonial)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'testimonials';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        items?: (number | Service)[] | null;
        /**
         * Optional. When set, renders 3-col with image in middle.
         */
        centerImage?: (number | null) | Media;
        id?: string | null;
        blockName?: string | null;
        blockType: 'services';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        items?:
          | {
              icon?:
                | ('spark' | 'shield' | 'chart' | 'users' | 'compass' | 'flag' | 'brain' | 'layers' | 'cpu' | 'star')
                | null;
              title: string;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'features';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        items?:
          | {
              /**
               * Ảnh icon (ưu tiên). Để trống thì dùng "Image URL".
               */
              image?: (number | null) | Media;
              /**
               * Đường dẫn ảnh tĩnh, vd /images/trang-chu/khac-biet-150.png
               */
              imageUrl?: string | null;
              title: string;
              body?: string | null;
              /**
               * Vd: Xem thêm
               */
              linkLabel?: string | null;
              /**
               * Vd: /keystone
               */
              linkHref?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureCards';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        /**
         * Ảnh lớn bên trái (ưu tiên). Để trống thì dùng "Image URL".
         */
        image?: (number | null) | Media;
        /**
         * Đường dẫn ảnh tĩnh bên trái, vd /images/trang-chu/chose-bg.jpg
         */
        imageUrl?: string | null;
        items?:
          | {
              /**
               * Icon ảnh (ưu tiên). Để trống thì dùng "Icon URL".
               */
              image?: (number | null) | Media;
              /**
               * Đường dẫn icon tĩnh, vd /images/trang-chu/chuong-trinh-chat-luong-80x80.png
               */
              imageUrl?: string | null;
              title: string;
              body?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'featureList';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        display?: ('accordion' | 'grid') | null;
        groups?:
          | {
              icon?:
                | ('spark' | 'shield' | 'chart' | 'users' | 'compass' | 'flag' | 'brain' | 'layers' | 'cpu' | 'star')
                | null;
              title: string;
              description?: string | null;
              items?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'categoryList';
      }
    | {
        image: number | Media;
        caption?: string | null;
        /**
         * Full browser width (no container)
         */
        fullBleed?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'image';
      }
    | {
        imagePosition?: ('right' | 'left') | null;
        eyebrow?: string | null;
        title?: string | null;
        paragraphs?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Optional bullet list.
         */
        bullets?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        image?: (number | null) | Media;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        background?: ('white' | 'light' | 'navy') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'split';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        /**
         * Grid hiển thị dạng lưới, Slider hiển thị dạng trượt ngang.
         */
        display?: ('grid' | 'slider') | null;
        /**
         * Number of recent posts to show.
         */
        limit?: number | null;
        /**
         * Optional. Pinned posts. If empty, shows latest by date.
         */
        pinned?: (number | Post)[] | null;
        /**
         * Bật phân trang (chỉ áp dụng cho Grid). Limit trở thành số bài / trang.
         */
        paginate?: boolean | null;
        ctaLabel?: string | null;
        ctaHref?: string | null;
        /**
         * Tự động chuyển slide.
         */
        autoplay?: boolean | null;
        /**
         * Tốc độ autoplay (ms).
         */
        autoplaySpeed?: number | null;
        /**
         * Lặp vô hạn (loop).
         */
        loop?: boolean | null;
        /**
         * Số slide hiển thị cùng lúc (desktop).
         */
        slidesPerView?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'posts';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        /**
         * Số sự kiện hiển thị mỗi trang.
         */
        perPage?: number | null;
        /**
         * Hiện sidebar (tìm kiếm, danh mục, archive).
         */
        showSidebar?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'events';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        items?: (number | Partner)[] | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'partners';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        /**
         * Google Maps embed URL (src của iframe).
         */
        embedUrl: string;
        /**
         * Chiều cao iframe (px).
         */
        height?: number | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'map';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        description?: string | null;
        submitLabel?: string | null;
        successMessage?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contactForm';
      }
    | {
        eyebrow?: string | null;
        title?: string | null;
        /**
         * VD: Cập nhật lần cuối: 27/05/2026
         */
        updatedAt?: string | null;
        intro?: string | null;
        sections?:
          | {
              title: string;
              paragraphs?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              items?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'legalDoc';
      }
    | {
        title: string;
        body?: string | null;
        buttonLabel?: string | null;
        buttonHref?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cta';
      }
  )[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  email: string;
  subject?: string | null;
  message: string;
  status?: ('new' | 'in-progress' | 'resolved' | 'spam') | null;
  /**
   * Ghi chú nội bộ.
   */
  note?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  thumbnail?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  author?: T;
  publishedAt?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  thumbnail?: T;
  categories?: T;
  eventDate?: T;
  location?: T;
  excerpt?: T;
  content?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  icon?: T;
  shortDescription?: T;
  content?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  thumbnail?: T;
  duration?: T;
  level?: T;
  description?: T;
  price?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  company?: T;
  avatar?: T;
  quote?: T;
  rating?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  photo?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        jsonLdSchema?: T;
      };
  layout?:
    | T
    | {
        heroSlider?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    badge?: T;
                    headline?: T;
                    sub?: T;
                    ctaLabel?: T;
                    ctaHref?: T;
                    id?: T;
                  };
              autoplayMs?: T;
              id?: T;
              blockName?: T;
            };
        hero?:
          | T
          | {
              breadcrumb?: T;
              title?: T;
              subtitle?: T;
              variant?: T;
              backgroundImage?: T;
              id?: T;
              blockName?: T;
            };
        intro?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              keywords?:
                | T
                | {
                    label?: T;
                    id?: T;
                  };
              blockquote?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              background?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              members?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        services?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?: T;
              centerImage?: T;
              id?: T;
              blockName?: T;
            };
        features?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureCards?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    image?: T;
                    imageUrl?: T;
                    title?: T;
                    body?: T;
                    linkLabel?: T;
                    linkHref?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        featureList?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              image?: T;
              imageUrl?: T;
              items?:
                | T
                | {
                    image?: T;
                    imageUrl?: T;
                    title?: T;
                    body?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        categoryList?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              display?: T;
              groups?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    items?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              caption?: T;
              fullBleed?: T;
              id?: T;
              blockName?: T;
            };
        split?:
          | T
          | {
              imagePosition?: T;
              eyebrow?: T;
              title?: T;
              paragraphs?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              ctaLabel?: T;
              ctaHref?: T;
              background?: T;
              id?: T;
              blockName?: T;
            };
        posts?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              display?: T;
              limit?: T;
              pinned?: T;
              paginate?: T;
              ctaLabel?: T;
              ctaHref?: T;
              autoplay?: T;
              autoplaySpeed?: T;
              loop?: T;
              slidesPerView?: T;
              id?: T;
              blockName?: T;
            };
        events?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              perPage?: T;
              showSidebar?: T;
              id?: T;
              blockName?: T;
            };
        partners?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?: T;
              id?: T;
              blockName?: T;
            };
        map?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              embedUrl?: T;
              height?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              submitLabel?: T;
              successMessage?: T;
              id?: T;
              blockName?: T;
            };
        legalDoc?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              updatedAt?: T;
              intro?: T;
              sections?:
                | T
                | {
                    title?: T;
                    paragraphs?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    items?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              body?: T;
              buttonLabel?: T;
              buttonHref?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  status?: T;
  note?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName?: string | null;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  hotline?: string | null;
  email?: string | null;
  address?: string | null;
  workingHours?: string | null;
  socialLinks?: {
    facebook?: string | null;
    youtube?: string | null;
    linkedin?: string | null;
    zalo?: string | null;
  };
  footer?: {
    logo?: (number | null) | Media;
    slogan?: string | null;
    subSlogan?: string | null;
    legalName?: string | null;
    representative?: string | null;
    /**
     * Mỗi badge: tải ảnh lên HOẶC dán URL ảnh ngoài (vd DMCA).
     */
    badges?:
      | {
          image?: (number | null) | Media;
          /**
           * Dùng khi ảnh nằm ở dịch vụ ngoài, vd images.dmca.com.
           */
          imageUrl?: string | null;
          link?: string | null;
          alt?: string | null;
          whiteBg?: boolean | null;
          height?: number | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    headline?: string | null;
    subheadline?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    backgroundImage?: (number | null) | Media;
  };
  aboutSection?: {
    title?: string | null;
    content?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    image?: (number | null) | Media;
    stats?:
      | {
          label?: string | null;
          value?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  valuesSection?: {
    items?:
      | {
          icon?: string | null;
          title?: string | null;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seoTitle?: string | null;
  seoDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  topBar?: {
    phone?: string | null;
    email?: string | null;
    workingHours?: string | null;
  };
  menuItems?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  ctaButton?: {
    label?: string | null;
    link?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  hotline?: T;
  email?: T;
  address?: T;
  workingHours?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        youtube?: T;
        linkedin?: T;
        zalo?: T;
      };
  footer?:
    | T
    | {
        logo?: T;
        slogan?: T;
        subSlogan?: T;
        legalName?: T;
        representative?: T;
        badges?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              link?: T;
              alt?: T;
              whiteBg?: T;
              height?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        ctaText?: T;
        ctaLink?: T;
        backgroundImage?: T;
      };
  aboutSection?:
    | T
    | {
        title?: T;
        content?: T;
        image?: T;
        stats?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
      };
  valuesSection?:
    | T
    | {
        items?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  topBar?:
    | T
    | {
        phone?: T;
        email?: T;
        workingHours?: T;
      };
  menuItems?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  ctaButton?:
    | T
    | {
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}